---
- name: dev-all
  hosts: Dev
  connection: ssh
  remote_user: ansi
  # become: true
  # become_method: sudo
  tasks:
    - name: Testing for distro...
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_machine }}) Family: {{ ansible_os_family }}"

# - name: dev-rpm
#   hosts: rpm
#   connection: ssh
#   remote_user: root
#   become: true
#   # become_method: sudo
#   tasks:
#     - name: Testing for distro...
#       debug:
#         msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_machine }}) Family: {{ ansible_os_family }}"
#
# - name: dev-deb
#   hosts: deb
#   connection: ssh
#   remote_user: dude
#   become: true
#   # become_method: sudo
#   tasks:
#     - name: Testing for distro...
#       debug:
#         msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_machine }}) Family: {{ ansible_os_family }}"
#
# - name: dev-ubuntu
#   hosts: ubnt
#   connection: ssh
#   remote_user: dude
#   become: true
#   become_method: sudo
#   tasks:
#     - name: Testing for distro...
#       debug:
#         msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_machine }}) Family: {{ ansible_os_family }}"
