# ВНИМАНИЕ! Потенциально опасно! ТОЛЬКО НА СВОЙ СТРАХ И РИСК!
# Применять ТОЛЬКО в DEV средах!!!
---
- hosts: all
  remote_user: ansi
  become: yes

  vars:
    probe_timeout: 300

  tasks:
  - name: Обновляем систему Debian...
    apt:
      upgrade: dist
    when:
      ansible_facts['os_family'] == "Debian"

  - name: Обновляем систему RedHat <= 7...
    yum:
      name: '*'
      state: latest
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution_major_version'] <= "7"

  - name: Обновляем систему RedHat > 7...
    dnf:
      name: '*'
      state: latest
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution_major_version'] > "7"

  - name: Перезагружаем по необходимости Debian...
    include_role:
      name: ansible-reboot-if-needed-for-upgrade
