- name: "Tasks for {{ ansible_os_family }} OS-Family..."
  debug:
    msg:
      - "{{ ansible_os_family }} : {{ ansible_os_family | type_debug }}"
      - "{{ ansible_distribution }} : {{ ansible_distribution_version }}"
      - "{{ ansible_lsb }} : {{ ansible_lsb | type_debug }}"

- name: Test user dude...
  # ssh_user: dude
  command: whoami
  become: yes
  become_method: sudo
  register: reply

- debug:
    msg: var="{{ reply.stdout_lines }}"