- hosts: all
  tasks:
  - name: Set up authorized_keys for the ansi user
    authorized_key:
      user: ansi
      key: "{{ item }}"
    with_file:
    - ssh-keys/ansi.pub
    - ssh-keys/id_ed25519.pub
    - ssh-keys/avd-tpe14_ed25519.pub
