- hosts: dev
  become: yes
  become_method: sudo
  tasks:
  - name: Install additional packages
    apt:
      name:
        - sudo
        - vim
        - glances
        - htop
        - byobu
        - mc
      state: latest
