- hosts: k8s
  become: yes
  become_method: sudo
  tasks:
  - name: Set {{ cluster_host }} as hostname
    hostname:
      name: "{{ cluster_host }}"
  - name: Edit /etc/hosts for 'SUPERLOCAL'loopback
    lineinfile:
      path: /etc/hosts
      state: present
      regexp: '^127\.0\.1\.1\s'
      line: "127.0.1.1 {{ cluster_host }} {{ cluster_host }}.k8s.loc"
