- hosts: kvm
  become: yes
  become_method: sudo
  tasks:
  - name: Install KVM additions
    apt:
      name: ['xserver-xorg-video-qxl', 'spice-vdagent']
      state: latest
- hosts: vmware
  tasks:
  - name: Install VMWare additions
    apt:
      name: ['open-vm-tools']
      state: latest
